FROM ashdev/docker-nodejs:v4.2.2
MAINTAINER AshDev <ashdevfr@gmail.com>

RUN npm i -g gulp nodemon bower

ENV workdir_path /home/workspace
WORKDIR ${workdir_path}/

ADD .bowerrc ${workdir_path}/
ADD .eslintrc ${workdir_path}/
ADD bower.json ${workdir_path}/
ADD gulpfile.js ${workdir_path}/
ADD karma.conf.js ${workdir_path}/
ADD package.json ${workdir_path}/
ADD protractor.conf.js ${workdir_path}/
ADD README.md ${workdir_path}/
ADD gulp ${workdir_path}/gulp

RUN git config --global url."https://".insteadOf git://

RUN npm install

RUN bower install --config.interactive=false --allow-root

EXPOSE 3000 3001 3010

VOLUME ${workdir_path}

ENTRYPOINT ["gulp"]

CMD ["help"]
